import {auth,db,firebaseReady} from '../firebase/firebase-config.js';
import {signInWithEmailAndPassword,signOut,getIdTokenResult} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
import {collection,getDocs,query,orderBy,limit} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
const modal=document.querySelector('#admin-modal'),loginView=document.querySelector('#admin-login-view'),dashboardView=document.querySelector('#admin-dashboard-view'),content=document.querySelector('#admin-modal-content');
const toast=message=>{const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),3500)};
const close=()=>{modal.hidden=true};document.querySelector('#open-admin').onclick=()=>{modal.hidden=false};document.querySelector('#close-admin').onclick=close;modal.onclick=event=>{if(event.target===modal)close()};
async function dashboard(){const summary=document.createElement('div');summary.className='admin-summary';if(!firebaseReady){summary.textContent='Configure o Firebase para ativar o painel.';content.replaceChildren(summary);return}try{const [quoteSnap,projectSnap]=await Promise.all([getDocs(query(collection(db,'quotes'),orderBy('criadoEm','desc'),limit(50))),getDocs(query(collection(db,'projects'),limit(50)))]);const quotes=quoteSnap.docs.map(d=>d.data());[['Orçamentos',quotes.length],['Novos',quotes.filter(q=>q.status==='novo').length],['Projetos',projectSnap.size]].forEach(([label,value])=>{const card=document.createElement('div');card.className='admin-summary-card';const number=document.createElement('b');number.textContent=value;const text=document.createElement('span');text.textContent=label;card.append(number,text);summary.append(card)});content.replaceChildren(summary)}catch{content.textContent='Não foi possível carregar os dados do painel.'}}
async function showAdmin(user){const token=await getIdTokenResult(user,true);if(token.claims.admin!==true){await signOut(auth);throw new Error('Acesso não autorizado.')}loginView.hidden=true;dashboardView.hidden=false;await dashboard()}
document.querySelector('#admin-login-form').addEventListener('submit',async event=>{event.preventDefault();if(!firebaseReady)return toast('Configure o Firebase antes de entrar.');const button=event.currentTarget.querySelector('button');try{button.disabled=true;const result=await signInWithEmailAndPassword(auth,event.currentTarget.email.value.trim(),event.currentTarget.password.value);await showAdmin(result.user)}catch(error){toast(error.message||'Não foi possível entrar.')}finally{button.disabled=false}});document.querySelector('#admin-logout').onclick=async()=>{await signOut(auth);dashboardView.hidden=true;loginView.hidden=false;content.replaceChildren();toast('Sessão encerrada.')};
